  - name: openrouter/x-ai/grok-code-fast-1
    use_repo_map: true
    edit_format: diff
    weak_model_name: openrouter/x-ai/grok-code-fast-1
    accepts_settings:
      - reasoning_effort
    cache_control: true

  - name: openrouter/deepseek/deepseek-v3.2
    edit_format: diff
    weak_model_name: openrouter/deepseek/deepseek-v3.2
    use_repo_map: true
    send_undo_reply: true
    examples_as_sys_msg: true
    cache_control: true
